/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_FROM = 1,
  anon_sym_PARAMETER = 2,
  anon_sym_REQUIRES = 3,
  anon_sym_MESSAGE = 4,
  anon_sym_TEMPLATE = 5,
  anon_sym_SYSTEM = 6,
  anon_sym_LICENSE = 7,
  anon_sym_ADAPTER = 8,
  sym_model_ref = 9,
  sym_model_ref_with_tag = 10,
  sym_file_path = 11,
  sym_version = 12,
  anon_sym_num_ctx = 13,
  anon_sym_repeat_last_n = 14,
  anon_sym_repeat_penalty = 15,
  anon_sym_temperature = 16,
  anon_sym_seed = 17,
  anon_sym_stop = 18,
  anon_sym_num_predict = 19,
  anon_sym_top_k = 20,
  anon_sym_top_p = 21,
  anon_sym_min_p = 22,
  sym_argument = 23,
  sym_number = 24,
  sym_quoted_string = 25,
  anon_sym_DQUOTE_DQUOTE_DQUOTE = 26,
  aux_sym_multiline_string_token1 = 27,
  sym__newline = 28,
  sym_comment = 29,
  sym_source_file = 30,
  sym__instruction = 31,
  sym_from_instruction = 32,
  sym_parameter_instruction = 33,
  sym_requires_instruction = 34,
  sym_message_instruction = 35,
  sym_template_instruction = 36,
  sym_system_instruction = 37,
  sym_license_instruction = 38,
  sym_adapter_instruction = 39,
  sym_model_source = 40,
  sym_parameter = 41,
  sym_parameter_value = 42,
  sym_multiline_string = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_multiline_string_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_FROM] = "FROM",
  [anon_sym_PARAMETER] = "PARAMETER",
  [anon_sym_REQUIRES] = "REQUIRES",
  [anon_sym_MESSAGE] = "MESSAGE",
  [anon_sym_TEMPLATE] = "TEMPLATE",
  [anon_sym_SYSTEM] = "SYSTEM",
  [anon_sym_LICENSE] = "LICENSE",
  [anon_sym_ADAPTER] = "ADAPTER",
  [sym_model_ref] = "model_ref",
  [sym_model_ref_with_tag] = "model_ref_with_tag",
  [sym_file_path] = "file_path",
  [sym_version] = "version",
  [anon_sym_num_ctx] = "num_ctx",
  [anon_sym_repeat_last_n] = "repeat_last_n",
  [anon_sym_repeat_penalty] = "repeat_penalty",
  [anon_sym_temperature] = "temperature",
  [anon_sym_seed] = "seed",
  [anon_sym_stop] = "stop",
  [anon_sym_num_predict] = "num_predict",
  [anon_sym_top_k] = "top_k",
  [anon_sym_top_p] = "top_p",
  [anon_sym_min_p] = "min_p",
  [sym_argument] = "argument",
  [sym_number] = "number",
  [sym_quoted_string] = "quoted_string",
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = "\"\"\"",
  [aux_sym_multiline_string_token1] = "multiline_string_token1",
  [sym__newline] = "_newline",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__instruction] = "_instruction",
  [sym_from_instruction] = "from_instruction",
  [sym_parameter_instruction] = "parameter_instruction",
  [sym_requires_instruction] = "requires_instruction",
  [sym_message_instruction] = "message_instruction",
  [sym_template_instruction] = "template_instruction",
  [sym_system_instruction] = "system_instruction",
  [sym_license_instruction] = "license_instruction",
  [sym_adapter_instruction] = "adapter_instruction",
  [sym_model_source] = "model_source",
  [sym_parameter] = "parameter",
  [sym_parameter_value] = "parameter_value",
  [sym_multiline_string] = "multiline_string",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_multiline_string_repeat1] = "multiline_string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_FROM] = anon_sym_FROM,
  [anon_sym_PARAMETER] = anon_sym_PARAMETER,
  [anon_sym_REQUIRES] = anon_sym_REQUIRES,
  [anon_sym_MESSAGE] = anon_sym_MESSAGE,
  [anon_sym_TEMPLATE] = anon_sym_TEMPLATE,
  [anon_sym_SYSTEM] = anon_sym_SYSTEM,
  [anon_sym_LICENSE] = anon_sym_LICENSE,
  [anon_sym_ADAPTER] = anon_sym_ADAPTER,
  [sym_model_ref] = sym_model_ref,
  [sym_model_ref_with_tag] = sym_model_ref_with_tag,
  [sym_file_path] = sym_file_path,
  [sym_version] = sym_version,
  [anon_sym_num_ctx] = anon_sym_num_ctx,
  [anon_sym_repeat_last_n] = anon_sym_repeat_last_n,
  [anon_sym_repeat_penalty] = anon_sym_repeat_penalty,
  [anon_sym_temperature] = anon_sym_temperature,
  [anon_sym_seed] = anon_sym_seed,
  [anon_sym_stop] = anon_sym_stop,
  [anon_sym_num_predict] = anon_sym_num_predict,
  [anon_sym_top_k] = anon_sym_top_k,
  [anon_sym_top_p] = anon_sym_top_p,
  [anon_sym_min_p] = anon_sym_min_p,
  [sym_argument] = sym_argument,
  [sym_number] = sym_number,
  [sym_quoted_string] = sym_quoted_string,
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = anon_sym_DQUOTE_DQUOTE_DQUOTE,
  [aux_sym_multiline_string_token1] = aux_sym_multiline_string_token1,
  [sym__newline] = sym__newline,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__instruction] = sym__instruction,
  [sym_from_instruction] = sym_from_instruction,
  [sym_parameter_instruction] = sym_parameter_instruction,
  [sym_requires_instruction] = sym_requires_instruction,
  [sym_message_instruction] = sym_message_instruction,
  [sym_template_instruction] = sym_template_instruction,
  [sym_system_instruction] = sym_system_instruction,
  [sym_license_instruction] = sym_license_instruction,
  [sym_adapter_instruction] = sym_adapter_instruction,
  [sym_model_source] = sym_model_source,
  [sym_parameter] = sym_parameter,
  [sym_parameter_value] = sym_parameter_value,
  [sym_multiline_string] = sym_multiline_string,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_multiline_string_repeat1] = aux_sym_multiline_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_FROM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PARAMETER] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_REQUIRES] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MESSAGE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TEMPLATE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SYSTEM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LICENSE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ADAPTER] = {
    .visible = true,
    .named = false,
  },
  [sym_model_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_model_ref_with_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_file_path] = {
    .visible = true,
    .named = true,
  },
  [sym_version] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_num_ctx] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_repeat_last_n] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_repeat_penalty] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_temperature] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_seed] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_stop] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_num_predict] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_top_k] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_top_p] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_min_p] = {
    .visible = true,
    .named = false,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE_DQUOTE_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_multiline_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__instruction] = {
    .visible = false,
    .named = true,
  },
  [sym_from_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_requires_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_message_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_template_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_system_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_license_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_adapter_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_model_source] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_value] = {
    .visible = true,
    .named = true,
  },
  [sym_multiline_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_multiline_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(121);
      ADVANCE_MAP(
        '"', 2,
        '#', 159,
        '-', 116,
        '.', 13,
        '/', 120,
        'A', 20,
        'F', 46,
        'L', 34,
        'M', 21,
        'P', 16,
        'R', 22,
        'S', 61,
        'T', 23,
        'm', 84,
        'n', 110,
        'r', 75,
        's', 79,
        't', 81,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(149);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(158);
      if (lookahead == '#') ADVANCE(159);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(152);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(153);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(151);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '#') ADVANCE(159);
      if (lookahead == '.') ADVANCE(130);
      if (lookahead == '/') ADVANCE(120);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(131);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(156);
      if (lookahead == '#') ADVANCE(157);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(155);
      if (lookahead != 0) ADVANCE(154);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '#') ADVANCE(159);
      if (lookahead == '-') ADVANCE(116);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(147);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(3);
      END_STATE();
    case 9:
      if (lookahead == '#') ADVANCE(159);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(9);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == '#') ADVANCE(145);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(10);
      if (lookahead != 0) ADVANCE(146);
      END_STATE();
    case 11:
      if (lookahead == '.') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      if (lookahead == '.') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      if (lookahead == '/') ADVANCE(120);
      END_STATE();
    case 14:
      if (lookahead == 'A') ADVANCE(44);
      END_STATE();
    case 15:
      if (lookahead == 'A') ADVANCE(33);
      END_STATE();
    case 16:
      if (lookahead == 'A') ADVANCE(49);
      END_STATE();
    case 17:
      if (lookahead == 'A') ADVANCE(40);
      END_STATE();
    case 18:
      if (lookahead == 'A') ADVANCE(59);
      END_STATE();
    case 19:
      if (lookahead == 'C') ADVANCE(24);
      END_STATE();
    case 20:
      if (lookahead == 'D') ADVANCE(14);
      END_STATE();
    case 21:
      if (lookahead == 'E') ADVANCE(53);
      END_STATE();
    case 22:
      if (lookahead == 'E') ADVANCE(45);
      END_STATE();
    case 23:
      if (lookahead == 'E') ADVANCE(39);
      END_STATE();
    case 24:
      if (lookahead == 'E') ADVANCE(41);
      END_STATE();
    case 25:
      if (lookahead == 'E') ADVANCE(128);
      END_STATE();
    case 26:
      if (lookahead == 'E') ADVANCE(125);
      END_STATE();
    case 27:
      if (lookahead == 'E') ADVANCE(126);
      END_STATE();
    case 28:
      if (lookahead == 'E') ADVANCE(47);
      END_STATE();
    case 29:
      if (lookahead == 'E') ADVANCE(38);
      END_STATE();
    case 30:
      if (lookahead == 'E') ADVANCE(48);
      END_STATE();
    case 31:
      if (lookahead == 'E') ADVANCE(52);
      END_STATE();
    case 32:
      if (lookahead == 'E') ADVANCE(58);
      END_STATE();
    case 33:
      if (lookahead == 'G') ADVANCE(26);
      END_STATE();
    case 34:
      if (lookahead == 'I') ADVANCE(19);
      END_STATE();
    case 35:
      if (lookahead == 'I') ADVANCE(50);
      END_STATE();
    case 36:
      if (lookahead == 'L') ADVANCE(18);
      END_STATE();
    case 37:
      if (lookahead == 'M') ADVANCE(122);
      END_STATE();
    case 38:
      if (lookahead == 'M') ADVANCE(127);
      END_STATE();
    case 39:
      if (lookahead == 'M') ADVANCE(43);
      END_STATE();
    case 40:
      if (lookahead == 'M') ADVANCE(32);
      END_STATE();
    case 41:
      if (lookahead == 'N') ADVANCE(55);
      END_STATE();
    case 42:
      if (lookahead == 'O') ADVANCE(37);
      END_STATE();
    case 43:
      if (lookahead == 'P') ADVANCE(36);
      END_STATE();
    case 44:
      if (lookahead == 'P') ADVANCE(57);
      END_STATE();
    case 45:
      if (lookahead == 'Q') ADVANCE(60);
      END_STATE();
    case 46:
      if (lookahead == 'R') ADVANCE(42);
      END_STATE();
    case 47:
      if (lookahead == 'R') ADVANCE(129);
      END_STATE();
    case 48:
      if (lookahead == 'R') ADVANCE(123);
      END_STATE();
    case 49:
      if (lookahead == 'R') ADVANCE(17);
      END_STATE();
    case 50:
      if (lookahead == 'R') ADVANCE(31);
      END_STATE();
    case 51:
      if (lookahead == 'S') ADVANCE(56);
      END_STATE();
    case 52:
      if (lookahead == 'S') ADVANCE(124);
      END_STATE();
    case 53:
      if (lookahead == 'S') ADVANCE(54);
      END_STATE();
    case 54:
      if (lookahead == 'S') ADVANCE(15);
      END_STATE();
    case 55:
      if (lookahead == 'S') ADVANCE(25);
      END_STATE();
    case 56:
      if (lookahead == 'T') ADVANCE(29);
      END_STATE();
    case 57:
      if (lookahead == 'T') ADVANCE(28);
      END_STATE();
    case 58:
      if (lookahead == 'T') ADVANCE(30);
      END_STATE();
    case 59:
      if (lookahead == 'T') ADVANCE(27);
      END_STATE();
    case 60:
      if (lookahead == 'U') ADVANCE(35);
      END_STATE();
    case 61:
      if (lookahead == 'Y') ADVANCE(51);
      END_STATE();
    case 62:
      if (lookahead == '_') ADVANCE(71);
      END_STATE();
    case 63:
      if (lookahead == '_') ADVANCE(86);
      END_STATE();
    case 64:
      if (lookahead == '_') ADVANCE(87);
      END_STATE();
    case 65:
      if (lookahead == '_') ADVANCE(92);
      END_STATE();
    case 66:
      if (lookahead == '_') ADVANCE(96);
      END_STATE();
    case 67:
      if (lookahead == 'a') ADVANCE(103);
      END_STATE();
    case 68:
      if (lookahead == 'a') ADVANCE(88);
      END_STATE();
    case 69:
      if (lookahead == 'a') ADVANCE(108);
      END_STATE();
    case 70:
      if (lookahead == 'a') ADVANCE(107);
      END_STATE();
    case 71:
      if (lookahead == 'c') ADVANCE(104);
      if (lookahead == 'p') ADVANCE(100);
      END_STATE();
    case 72:
      if (lookahead == 'c') ADVANCE(105);
      END_STATE();
    case 73:
      if (lookahead == 'd') ADVANCE(139);
      END_STATE();
    case 74:
      if (lookahead == 'd') ADVANCE(85);
      END_STATE();
    case 75:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 76:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 77:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 78:
      if (lookahead == 'e') ADVANCE(138);
      END_STATE();
    case 79:
      if (lookahead == 'e') ADVANCE(76);
      if (lookahead == 't') ADVANCE(94);
      END_STATE();
    case 80:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 81:
      if (lookahead == 'e') ADVANCE(90);
      if (lookahead == 'o') ADVANCE(98);
      END_STATE();
    case 82:
      if (lookahead == 'e') ADVANCE(74);
      END_STATE();
    case 83:
      if (lookahead == 'e') ADVANCE(102);
      END_STATE();
    case 84:
      if (lookahead == 'i') ADVANCE(91);
      END_STATE();
    case 85:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 86:
      if (lookahead == 'k') ADVANCE(142);
      if (lookahead == 'p') ADVANCE(143);
      END_STATE();
    case 87:
      if (lookahead == 'l') ADVANCE(67);
      if (lookahead == 'p') ADVANCE(80);
      END_STATE();
    case 88:
      if (lookahead == 'l') ADVANCE(106);
      END_STATE();
    case 89:
      if (lookahead == 'm') ADVANCE(62);
      END_STATE();
    case 90:
      if (lookahead == 'm') ADVANCE(99);
      END_STATE();
    case 91:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 92:
      if (lookahead == 'n') ADVANCE(136);
      END_STATE();
    case 93:
      if (lookahead == 'n') ADVANCE(68);
      END_STATE();
    case 94:
      if (lookahead == 'o') ADVANCE(95);
      END_STATE();
    case 95:
      if (lookahead == 'p') ADVANCE(140);
      END_STATE();
    case 96:
      if (lookahead == 'p') ADVANCE(144);
      END_STATE();
    case 97:
      if (lookahead == 'p') ADVANCE(77);
      END_STATE();
    case 98:
      if (lookahead == 'p') ADVANCE(63);
      END_STATE();
    case 99:
      if (lookahead == 'p') ADVANCE(83);
      END_STATE();
    case 100:
      if (lookahead == 'r') ADVANCE(82);
      END_STATE();
    case 101:
      if (lookahead == 'r') ADVANCE(78);
      END_STATE();
    case 102:
      if (lookahead == 'r') ADVANCE(70);
      END_STATE();
    case 103:
      if (lookahead == 's') ADVANCE(109);
      END_STATE();
    case 104:
      if (lookahead == 't') ADVANCE(112);
      END_STATE();
    case 105:
      if (lookahead == 't') ADVANCE(141);
      END_STATE();
    case 106:
      if (lookahead == 't') ADVANCE(113);
      END_STATE();
    case 107:
      if (lookahead == 't') ADVANCE(111);
      END_STATE();
    case 108:
      if (lookahead == 't') ADVANCE(64);
      END_STATE();
    case 109:
      if (lookahead == 't') ADVANCE(65);
      END_STATE();
    case 110:
      if (lookahead == 'u') ADVANCE(89);
      END_STATE();
    case 111:
      if (lookahead == 'u') ADVANCE(101);
      END_STATE();
    case 112:
      if (lookahead == 'x') ADVANCE(135);
      END_STATE();
    case 113:
      if (lookahead == 'y') ADVANCE(137);
      END_STATE();
    case 114:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(150);
      END_STATE();
    case 115:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      END_STATE();
    case 116:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(147);
      END_STATE();
    case 117:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(148);
      END_STATE();
    case 118:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 119:
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 120:
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(133);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(anon_sym_FROM);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(anon_sym_PARAMETER);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(anon_sym_REQUIRES);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(anon_sym_MESSAGE);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(anon_sym_TEMPLATE);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(anon_sym_SYSTEM);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(anon_sym_LICENSE);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(anon_sym_ADAPTER);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_model_ref);
      if (lookahead == '/') ADVANCE(120);
      if (lookahead == ':') ADVANCE(119);
      if (('-' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(131);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_model_ref);
      if (lookahead == ':') ADVANCE(119);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(131);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_model_ref_with_tag);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(132);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_file_path);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(133);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_version);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(anon_sym_num_ctx);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(anon_sym_repeat_last_n);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(anon_sym_repeat_penalty);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(anon_sym_temperature);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(anon_sym_seed);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(anon_sym_stop);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(anon_sym_num_predict);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(anon_sym_top_k);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(anon_sym_top_p);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(anon_sym_min_p);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_argument);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(159);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(145);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_argument);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(146);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(147);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(148);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(149);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(150);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_quoted_string);
      if (lookahead == '"') ADVANCE(153);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(anon_sym_DQUOTE_DQUOTE_DQUOTE);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_multiline_string_token1);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(aux_sym_multiline_string_token1);
      if (lookahead == '"') ADVANCE(156);
      if (lookahead == '#') ADVANCE(157);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(155);
      if (lookahead != 0) ADVANCE(154);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(aux_sym_multiline_string_token1);
      if (lookahead == '"') ADVANCE(3);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(aux_sym_multiline_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(159);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym__newline);
      if (lookahead == '\n') ADVANCE(158);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(159);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 7},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 9},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_FROM] = ACTIONS(1),
    [anon_sym_PARAMETER] = ACTIONS(1),
    [anon_sym_REQUIRES] = ACTIONS(1),
    [anon_sym_MESSAGE] = ACTIONS(1),
    [anon_sym_TEMPLATE] = ACTIONS(1),
    [anon_sym_SYSTEM] = ACTIONS(1),
    [anon_sym_LICENSE] = ACTIONS(1),
    [anon_sym_ADAPTER] = ACTIONS(1),
    [sym_file_path] = ACTIONS(1),
    [sym_version] = ACTIONS(1),
    [anon_sym_num_ctx] = ACTIONS(1),
    [anon_sym_repeat_last_n] = ACTIONS(1),
    [anon_sym_repeat_penalty] = ACTIONS(1),
    [anon_sym_temperature] = ACTIONS(1),
    [anon_sym_seed] = ACTIONS(1),
    [anon_sym_stop] = ACTIONS(1),
    [anon_sym_num_predict] = ACTIONS(1),
    [anon_sym_top_k] = ACTIONS(1),
    [anon_sym_top_p] = ACTIONS(1),
    [anon_sym_min_p] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [anon_sym_DQUOTE_DQUOTE_DQUOTE] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym__instruction] = STATE(16),
    [sym_from_instruction] = STATE(16),
    [sym_parameter_instruction] = STATE(16),
    [sym_requires_instruction] = STATE(16),
    [sym_message_instruction] = STATE(16),
    [sym_template_instruction] = STATE(16),
    [sym_system_instruction] = STATE(16),
    [sym_license_instruction] = STATE(16),
    [sym_adapter_instruction] = STATE(16),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_FROM] = ACTIONS(7),
    [anon_sym_PARAMETER] = ACTIONS(9),
    [anon_sym_REQUIRES] = ACTIONS(11),
    [anon_sym_MESSAGE] = ACTIONS(13),
    [anon_sym_TEMPLATE] = ACTIONS(15),
    [anon_sym_SYSTEM] = ACTIONS(17),
    [anon_sym_LICENSE] = ACTIONS(19),
    [anon_sym_ADAPTER] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_FROM,
    ACTIONS(9), 1,
      anon_sym_PARAMETER,
    ACTIONS(11), 1,
      anon_sym_REQUIRES,
    ACTIONS(13), 1,
      anon_sym_MESSAGE,
    ACTIONS(15), 1,
      anon_sym_TEMPLATE,
    ACTIONS(17), 1,
      anon_sym_SYSTEM,
    ACTIONS(19), 1,
      anon_sym_LICENSE,
    ACTIONS(21), 1,
      anon_sym_ADAPTER,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(16), 9,
      sym__instruction,
      sym_from_instruction,
      sym_parameter_instruction,
      sym_requires_instruction,
      sym_message_instruction,
      sym_template_instruction,
      sym_system_instruction,
      sym_license_instruction,
      sym_adapter_instruction,
  [45] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      anon_sym_FROM,
    ACTIONS(30), 1,
      anon_sym_PARAMETER,
    ACTIONS(33), 1,
      anon_sym_REQUIRES,
    ACTIONS(36), 1,
      anon_sym_MESSAGE,
    ACTIONS(39), 1,
      anon_sym_TEMPLATE,
    ACTIONS(42), 1,
      anon_sym_SYSTEM,
    ACTIONS(45), 1,
      anon_sym_LICENSE,
    ACTIONS(48), 1,
      anon_sym_ADAPTER,
    STATE(3), 1,
      aux_sym_source_file_repeat1,
    STATE(16), 9,
      sym__instruction,
      sym_from_instruction,
      sym_parameter_instruction,
      sym_requires_instruction,
      sym_message_instruction,
      sym_template_instruction,
      sym_system_instruction,
      sym_license_instruction,
      sym_adapter_instruction,
  [90] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(7), 1,
      sym_parameter,
    ACTIONS(51), 10,
      anon_sym_num_ctx,
      anon_sym_repeat_last_n,
      anon_sym_repeat_penalty,
      anon_sym_temperature,
      anon_sym_seed,
      anon_sym_stop,
      anon_sym_num_predict,
      anon_sym_top_k,
      anon_sym_top_p,
      anon_sym_min_p,
  [109] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(25), 9,
      ts_builtin_sym_end,
      anon_sym_FROM,
      anon_sym_PARAMETER,
      anon_sym_REQUIRES,
      anon_sym_MESSAGE,
      anon_sym_TEMPLATE,
      anon_sym_SYSTEM,
      anon_sym_LICENSE,
      anon_sym_ADAPTER,
  [124] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      sym_model_ref,
    STATE(19), 1,
      sym_model_source,
    ACTIONS(55), 2,
      sym_model_ref_with_tag,
      sym_file_path,
  [138] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(27), 1,
      sym_parameter_value,
    ACTIONS(57), 2,
      sym_number,
      sym_quoted_string,
  [149] = 4,
    ACTIONS(59), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(61), 1,
      aux_sym_multiline_string_token1,
    ACTIONS(63), 1,
      sym_comment,
    STATE(10), 1,
      aux_sym_multiline_string_repeat1,
  [162] = 4,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(65), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(67), 1,
      aux_sym_multiline_string_token1,
    STATE(9), 1,
      aux_sym_multiline_string_repeat1,
  [175] = 4,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    ACTIONS(72), 1,
      aux_sym_multiline_string_token1,
    STATE(9), 1,
      aux_sym_multiline_string_repeat1,
  [188] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(25), 1,
      sym_multiline_string,
  [198] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 2,
      sym_number,
      sym_quoted_string,
  [206] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(30), 1,
      sym_multiline_string,
  [216] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_DQUOTE_DQUOTE_DQUOTE,
    STATE(32), 1,
      sym_multiline_string,
  [226] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
  [233] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(80), 1,
      sym__newline,
  [240] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      sym_version,
  [247] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(84), 1,
      sym__newline,
  [254] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym__newline,
  [261] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(88), 1,
      sym_file_path,
  [268] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_argument,
  [275] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym__newline,
  [282] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(94), 1,
      sym_argument,
  [289] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(96), 1,
      sym__newline,
  [296] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(98), 1,
      sym__newline,
  [303] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(100), 1,
      sym__newline,
  [310] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(102), 1,
      sym__newline,
  [317] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(104), 1,
      sym__newline,
  [324] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(106), 1,
      sym__newline,
  [331] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(108), 1,
      sym__newline,
  [338] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(110), 1,
      sym__newline,
  [345] = 2,
    ACTIONS(63), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 90,
  [SMALL_STATE(5)] = 109,
  [SMALL_STATE(6)] = 124,
  [SMALL_STATE(7)] = 138,
  [SMALL_STATE(8)] = 149,
  [SMALL_STATE(9)] = 162,
  [SMALL_STATE(10)] = 175,
  [SMALL_STATE(11)] = 188,
  [SMALL_STATE(12)] = 198,
  [SMALL_STATE(13)] = 206,
  [SMALL_STATE(14)] = 216,
  [SMALL_STATE(15)] = 226,
  [SMALL_STATE(16)] = 233,
  [SMALL_STATE(17)] = 240,
  [SMALL_STATE(18)] = 247,
  [SMALL_STATE(19)] = 254,
  [SMALL_STATE(20)] = 261,
  [SMALL_STATE(21)] = 268,
  [SMALL_STATE(22)] = 275,
  [SMALL_STATE(23)] = 282,
  [SMALL_STATE(24)] = 289,
  [SMALL_STATE(25)] = 296,
  [SMALL_STATE(26)] = 303,
  [SMALL_STATE(27)] = 310,
  [SMALL_STATE(28)] = 317,
  [SMALL_STATE(29)] = 324,
  [SMALL_STATE(30)] = 331,
  [SMALL_STATE(31)] = 338,
  [SMALL_STATE(32)] = 345,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_multiline_string_repeat1, 2, 0, 0),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_multiline_string_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_model_source, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_from_instruction, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requires_instruction, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adapter_instruction, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_license_instruction, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_value, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_instruction, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_instruction, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_string, 2, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_instruction, 2, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_multiline_string, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_instruction, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_modelfile(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "modelfile",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
