/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 24
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LF = 1,
  anon_sym_FROM = 2,
  aux_sym_from_instruction_token1 = 3,
  anon_sym_PARAMETER = 4,
  anon_sym_REQUIRES = 5,
  anon_sym_MESSAGE = 6,
  anon_sym_TEMPLATE = 7,
  aux_sym_template_instruction_token1 = 8,
  anon_sym_SYSTEM = 9,
  anon_sym_ADAPTER = 10,
  sym_comment = 11,
  sym_source_file = 12,
  sym_instruction = 13,
  sym_from_instruction = 14,
  sym_parameter_instruction = 15,
  sym_requires_instruction = 16,
  sym_message_instruction = 17,
  sym_template_instruction = 18,
  sym_system_instruction = 19,
  sym_adapter_instruction = 20,
  aux_sym_source_file_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_FROM] = "FROM",
  [aux_sym_from_instruction_token1] = "from_instruction_token1",
  [anon_sym_PARAMETER] = "PARAMETER",
  [anon_sym_REQUIRES] = "REQUIRES",
  [anon_sym_MESSAGE] = "MESSAGE",
  [anon_sym_TEMPLATE] = "TEMPLATE",
  [aux_sym_template_instruction_token1] = "template_instruction_token1",
  [anon_sym_SYSTEM] = "SYSTEM",
  [anon_sym_ADAPTER] = "ADAPTER",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_instruction] = "instruction",
  [sym_from_instruction] = "from_instruction",
  [sym_parameter_instruction] = "parameter_instruction",
  [sym_requires_instruction] = "requires_instruction",
  [sym_message_instruction] = "message_instruction",
  [sym_template_instruction] = "template_instruction",
  [sym_system_instruction] = "system_instruction",
  [sym_adapter_instruction] = "adapter_instruction",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_FROM] = anon_sym_FROM,
  [aux_sym_from_instruction_token1] = aux_sym_from_instruction_token1,
  [anon_sym_PARAMETER] = anon_sym_PARAMETER,
  [anon_sym_REQUIRES] = anon_sym_REQUIRES,
  [anon_sym_MESSAGE] = anon_sym_MESSAGE,
  [anon_sym_TEMPLATE] = anon_sym_TEMPLATE,
  [aux_sym_template_instruction_token1] = aux_sym_template_instruction_token1,
  [anon_sym_SYSTEM] = anon_sym_SYSTEM,
  [anon_sym_ADAPTER] = anon_sym_ADAPTER,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_instruction] = sym_instruction,
  [sym_from_instruction] = sym_from_instruction,
  [sym_parameter_instruction] = sym_parameter_instruction,
  [sym_requires_instruction] = sym_requires_instruction,
  [sym_message_instruction] = sym_message_instruction,
  [sym_template_instruction] = sym_template_instruction,
  [sym_system_instruction] = sym_system_instruction,
  [sym_adapter_instruction] = sym_adapter_instruction,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_FROM] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_from_instruction_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PARAMETER] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_REQUIRES] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_MESSAGE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TEMPLATE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_template_instruction_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SYSTEM] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ADAPTER] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_from_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_requires_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_message_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_template_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_system_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_adapter_instruction] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(48);
      ADVANCE_MAP(
        '\n', 49,
        '"', 3,
        '#', 60,
        'A', 11,
        'F', 33,
        'M', 12,
        'P', 8,
        'R', 13,
        'S', 47,
        'T', 14,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(5);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(57);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(1);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == 'A') ADVANCE(31);
      END_STATE();
    case 7:
      if (lookahead == 'A') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 'A') ADVANCE(36);
      END_STATE();
    case 9:
      if (lookahead == 'A') ADVANCE(28);
      END_STATE();
    case 10:
      if (lookahead == 'A') ADVANCE(45);
      END_STATE();
    case 11:
      if (lookahead == 'D') ADVANCE(6);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(40);
      END_STATE();
    case 13:
      if (lookahead == 'E') ADVANCE(32);
      END_STATE();
    case 14:
      if (lookahead == 'E') ADVANCE(27);
      END_STATE();
    case 15:
      if (lookahead == 'E') ADVANCE(55);
      END_STATE();
    case 16:
      if (lookahead == 'E') ADVANCE(56);
      END_STATE();
    case 17:
      if (lookahead == 'E') ADVANCE(34);
      END_STATE();
    case 18:
      if (lookahead == 'E') ADVANCE(39);
      END_STATE();
    case 19:
      if (lookahead == 'E') ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == 'E') ADVANCE(35);
      END_STATE();
    case 21:
      if (lookahead == 'E') ADVANCE(44);
      END_STATE();
    case 22:
      if (lookahead == 'G') ADVANCE(15);
      END_STATE();
    case 23:
      if (lookahead == 'I') ADVANCE(37);
      END_STATE();
    case 24:
      if (lookahead == 'L') ADVANCE(10);
      END_STATE();
    case 25:
      if (lookahead == 'M') ADVANCE(50);
      END_STATE();
    case 26:
      if (lookahead == 'M') ADVANCE(58);
      END_STATE();
    case 27:
      if (lookahead == 'M') ADVANCE(30);
      END_STATE();
    case 28:
      if (lookahead == 'M') ADVANCE(21);
      END_STATE();
    case 29:
      if (lookahead == 'O') ADVANCE(25);
      END_STATE();
    case 30:
      if (lookahead == 'P') ADVANCE(24);
      END_STATE();
    case 31:
      if (lookahead == 'P') ADVANCE(43);
      END_STATE();
    case 32:
      if (lookahead == 'Q') ADVANCE(46);
      END_STATE();
    case 33:
      if (lookahead == 'R') ADVANCE(29);
      END_STATE();
    case 34:
      if (lookahead == 'R') ADVANCE(59);
      END_STATE();
    case 35:
      if (lookahead == 'R') ADVANCE(53);
      END_STATE();
    case 36:
      if (lookahead == 'R') ADVANCE(9);
      END_STATE();
    case 37:
      if (lookahead == 'R') ADVANCE(18);
      END_STATE();
    case 38:
      if (lookahead == 'S') ADVANCE(42);
      END_STATE();
    case 39:
      if (lookahead == 'S') ADVANCE(54);
      END_STATE();
    case 40:
      if (lookahead == 'S') ADVANCE(41);
      END_STATE();
    case 41:
      if (lookahead == 'S') ADVANCE(7);
      END_STATE();
    case 42:
      if (lookahead == 'T') ADVANCE(19);
      END_STATE();
    case 43:
      if (lookahead == 'T') ADVANCE(17);
      END_STATE();
    case 44:
      if (lookahead == 'T') ADVANCE(20);
      END_STATE();
    case 45:
      if (lookahead == 'T') ADVANCE(16);
      END_STATE();
    case 46:
      if (lookahead == 'U') ADVANCE(23);
      END_STATE();
    case 47:
      if (lookahead == 'Y') ADVANCE(38);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_FROM);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_from_instruction_token1);
      if (lookahead == '#') ADVANCE(52);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_from_instruction_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_PARAMETER);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_REQUIRES);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_MESSAGE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_TEMPLATE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_template_instruction_token1);
      if (lookahead == '"') ADVANCE(57);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_SYSTEM);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_ADAPTER);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(60);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 51},
  [6] = {.lex_state = 51},
  [7] = {.lex_state = 51},
  [8] = {.lex_state = 51},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 51},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 51},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 51},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_FROM] = ACTIONS(1),
    [anon_sym_PARAMETER] = ACTIONS(1),
    [anon_sym_REQUIRES] = ACTIONS(1),
    [anon_sym_MESSAGE] = ACTIONS(1),
    [anon_sym_TEMPLATE] = ACTIONS(1),
    [aux_sym_template_instruction_token1] = ACTIONS(1),
    [anon_sym_SYSTEM] = ACTIONS(1),
    [anon_sym_ADAPTER] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(12),
    [sym_instruction] = STATE(13),
    [sym_from_instruction] = STATE(14),
    [sym_parameter_instruction] = STATE(14),
    [sym_requires_instruction] = STATE(14),
    [sym_message_instruction] = STATE(14),
    [sym_template_instruction] = STATE(14),
    [sym_system_instruction] = STATE(14),
    [sym_adapter_instruction] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_FROM] = ACTIONS(7),
    [anon_sym_PARAMETER] = ACTIONS(9),
    [anon_sym_REQUIRES] = ACTIONS(11),
    [anon_sym_MESSAGE] = ACTIONS(13),
    [anon_sym_TEMPLATE] = ACTIONS(15),
    [anon_sym_SYSTEM] = ACTIONS(17),
    [anon_sym_ADAPTER] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_instruction] = STATE(13),
    [sym_from_instruction] = STATE(14),
    [sym_parameter_instruction] = STATE(14),
    [sym_requires_instruction] = STATE(14),
    [sym_message_instruction] = STATE(14),
    [sym_template_instruction] = STATE(14),
    [sym_system_instruction] = STATE(14),
    [sym_adapter_instruction] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [anon_sym_FROM] = ACTIONS(7),
    [anon_sym_PARAMETER] = ACTIONS(9),
    [anon_sym_REQUIRES] = ACTIONS(11),
    [anon_sym_MESSAGE] = ACTIONS(13),
    [anon_sym_TEMPLATE] = ACTIONS(15),
    [anon_sym_SYSTEM] = ACTIONS(17),
    [anon_sym_ADAPTER] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_instruction] = STATE(13),
    [sym_from_instruction] = STATE(14),
    [sym_parameter_instruction] = STATE(14),
    [sym_requires_instruction] = STATE(14),
    [sym_message_instruction] = STATE(14),
    [sym_template_instruction] = STATE(14),
    [sym_system_instruction] = STATE(14),
    [sym_adapter_instruction] = STATE(14),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_FROM] = ACTIONS(25),
    [anon_sym_PARAMETER] = ACTIONS(28),
    [anon_sym_REQUIRES] = ACTIONS(31),
    [anon_sym_MESSAGE] = ACTIONS(34),
    [anon_sym_TEMPLATE] = ACTIONS(37),
    [anon_sym_SYSTEM] = ACTIONS(40),
    [anon_sym_ADAPTER] = ACTIONS(43),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(23), 8,
      ts_builtin_sym_end,
      anon_sym_FROM,
      anon_sym_PARAMETER,
      anon_sym_REQUIRES,
      anon_sym_MESSAGE,
      anon_sym_TEMPLATE,
      anon_sym_SYSTEM,
      anon_sym_ADAPTER,
  [14] = 2,
    ACTIONS(46), 1,
      aux_sym_from_instruction_token1,
    ACTIONS(48), 1,
      sym_comment,
  [21] = 2,
    ACTIONS(48), 1,
      sym_comment,
    ACTIONS(50), 1,
      aux_sym_from_instruction_token1,
  [28] = 2,
    ACTIONS(48), 1,
      sym_comment,
    ACTIONS(52), 1,
      aux_sym_from_instruction_token1,
  [35] = 2,
    ACTIONS(48), 1,
      sym_comment,
    ACTIONS(54), 1,
      aux_sym_from_instruction_token1,
  [42] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      aux_sym_template_instruction_token1,
  [49] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      aux_sym_template_instruction_token1,
  [56] = 2,
    ACTIONS(48), 1,
      sym_comment,
    ACTIONS(60), 1,
      aux_sym_from_instruction_token1,
  [63] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
  [70] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(64), 1,
      anon_sym_LF,
  [77] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      anon_sym_LF,
  [84] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 1,
      anon_sym_LF,
  [91] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LF,
  [98] = 2,
    ACTIONS(48), 1,
      sym_comment,
    ACTIONS(72), 1,
      aux_sym_from_instruction_token1,
  [105] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      anon_sym_LF,
  [112] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(76), 1,
      anon_sym_LF,
  [119] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      anon_sym_LF,
  [126] = 2,
    ACTIONS(48), 1,
      sym_comment,
    ACTIONS(80), 1,
      aux_sym_from_instruction_token1,
  [133] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LF,
  [140] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 14,
  [SMALL_STATE(6)] = 21,
  [SMALL_STATE(7)] = 28,
  [SMALL_STATE(8)] = 35,
  [SMALL_STATE(9)] = 42,
  [SMALL_STATE(10)] = 49,
  [SMALL_STATE(11)] = 56,
  [SMALL_STATE(12)] = 63,
  [SMALL_STATE(13)] = 70,
  [SMALL_STATE(14)] = 77,
  [SMALL_STATE(15)] = 84,
  [SMALL_STATE(16)] = 91,
  [SMALL_STATE(17)] = 98,
  [SMALL_STATE(18)] = 105,
  [SMALL_STATE(19)] = 112,
  [SMALL_STATE(20)] = 119,
  [SMALL_STATE(21)] = 126,
  [SMALL_STATE(22)] = 133,
  [SMALL_STATE(23)] = 140,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [62] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_from_instruction, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_requires_instruction, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_instruction, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_system_instruction, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_adapter_instruction, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_instruction, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_instruction, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_modelfile(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "modelfile",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
